import org.apache.hadoop.fs.PathIOException;
public class FunctionUse19065 {
public void funcUse() {
PathIOException pathioexception = new PathIOException();
pathioexception.withFullyQualifiedPath(null);
}
}